############################
## CHANGE THESE
############################

baseURL: "https://department-of-meteorology-su.github.io/"
title: MISU

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
