############################
## CHANGE THESE
############################

baseURL: "https://Eisbrenner.github.io/templatetest"
title: templatetest

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
